CMB2.php
includes/CMB2_Sanitize.php

We found that when entering a single tick `'` into text fields, the resulting save adds an unnecessary escape character: `\'`
This is because of that weird legacy quirk with WordPress that forces magic quotes onto all incoming data, whether `$_GET` or `$_POST`. This happens regardless of the PHP setting so trying to use `get_magic_quotes_gpc()` in this context does not work. (See note here: http://codex.wordpress.org/Function_Reference/stripslashes_deep) 
This patch uses stripslashes_deep to nuke all of these befor storing fields in the database. We've tested and it works perfectly.

Run stripslashes before saving data, since WordPress forces magic quotes

---

example-functions.php
includes/CMB2_Field.php

In previous versions, multicheck fields were stored using multiple key/value entries. This was recently changed (maybe due to a bug) so now those fields got saved as serialized arrays. Unfortunately, that change made it impossible to use the "meta_key" and "meta_value" arguments with the get_posts function. 
This patch leaves the possbility to the user with an additional "multiple" option, to store the values as individual rows again.
Fixes #183
(Re-done to correct #225)

Add option to store values in individual rows instead of serialized array

---

init.php

Version 2.0.5 is 2.0.5 right? Since the class is *_205_trunk, should the VERSION constant be '2.0.5-trunk' also? or should this actually be 2.0.6-trunk since 2.0.5 is already tagged?

Update VERSION constant

---

includes/CMB2_Types.php

The function multicheck_inline in CMB2_Types.php must return the html element. Otherwise _render function doesn't echo anything.

Fix output the multicheck_inline field type

---

includes/CMB2_Sanitize.php

If an invalid timezone offset is used, fallback to UTC+0
This will catch both invalid timezones submitted from the field as well as an invalid timezone setting in WP that gets used when no timezone is selected from the dropdown.

Fallback for fatal error with invalid timezone

---

includes/CMB2_Field.php

This also streamlines how the field type is checked. Using `isset()` is more efficient than `in_array()`.

Add filter for non-repeatable fields

---

includes/CMB2_Types.php

I have a taxonomy with numeric terms — 0, 1, 2, 3, etc... — and the `taxonomy_select` option output was looking like this:
```html
<option value="" selected="selected">None</option>
<option value="0" selected="selected">0</option>
<option value="1">1</option>
```
Doing a strict comparison seems to fix the issue and only `None` gets selected. I can then select the `0` value and it is saved and selected correctly too.

taxonomy_select none option fix

---

includes/CMB2_Ajax.php
includes/helper-functions.php

CMB2_Ajax is already being used as a singleton, but doesn't enforce it which leads to the static `hooks()` function, so let's enforce it and be done with it.

Implement CMB2_Ajax as a singleton.

---

.travis.yml

Use unspecified PHP 7 minor in favour of specified one to ensure always using the latest available via Travis.

Update travis file for non-specific PHP minor

---

includes/CMB2_Field.php

Minor correction to typo of exempt in docblock for escaping_exception.

Correct spelling of exempt - was excempt

---

includes/CMB2_Sanitize.php

The number formatting of fields of the text_money type caused a money field to *always* be saved.
If the field was empty, it would be saved as '0.00'.
This fix allows for the proper (non-)saving of empty money fields.

Allow for optional/empty money field.

---

includes/helper-functions.php

Move the endpoint into the string for coherence, and if translators won't check the code, might add a double endpoint by mistake.

Small string improvement

---

includes/CMB2_Utils.php

Solve issues with asset paths on Windows/Xampp
The ABSPATH ($site_dir) is run through your normalize path function as you already do with $dir inside get_url_from_dir()
Fixes #676

Path issues with JS and CSS

---

includes/CMB2_hookup.php

When adding any of the cmb2 taxonomy_* metaboxes you get both the built in wp box and the cmb2 box.  This pull request gives a field option `remove_default`.
Is this the best place to hook this in?  Seemed logical to me but I'm not real familiar with cmb2 yet.

Adding field param option to remove WP default tax meta boxes

---

css/index.php
css/sass/index.php
css/sass/partials/index.php
images/index.php
includes/CMB2_Field.php
includes/CMB2_Types.php
includes/index.php
index.php
js/index.php
tests/index.php

Fixes #719 .
-  Add <?php opening tag to empty php files
-  Rename `CMB_Field->string()` function to `CMB_Field->get_string()` (string is a reserved keyword in PHP 7.0)

update files to be PHP7 compatible

---

includes/CMB2.php

You're missing $page_type variable :)

Fixed undefined variable: page_type

---

js/cmb2.js

Also fixed `Syntax error, unrecognized expression:` when call CMB2 in widget (ID key has contains `[`, `]` character)

Use quotes for label[for=""] selecttor

---

includes/CMB2_Base.php

Fixes #700.
Discussion: https://wordpress.org/support/topic/term-meta-is-saved-but-it-doesnt-appear-in-term-edit-screen-later/page/2/#post-8259773
So order matters here due to the caching pattern used in CMB2_
```
public function object_type( $object_type = '' ) {
if ( $object_type ) {
$this->object_type = $object_type;
return $this->object_type;
}
if ( $this->object_type ) {
return $this->object_type;
}
$this->object_type = $this->current_object_type();
return $this->object_type;
}
```
Which I think explains why different folks report different results.  Depending on the order things get initialized in, object_type could be set differently.
However, in the case where nothing else is setting object_type (this only happens during `render_form_open` and `render_form_close`), then in the …

Remove object_type default

---

includes/CMB2.php

to handle the 'add-tag' action of the 'admin-ajax.php' page.
Fixes #841.
-  Add a new check to see if the current page is `admin-ajax.php` and if an **action** parameter exists within the $_POST variable determine object-type based on it's value.
PS: AFAICT, there is only one entry point into the plugin's execution flow via the 'admin-ajax.php' page and this applies to this specific scenario / **term** object-type therefore the **action** parameter validation is sort of useless however, perhaps this might change in the near future so I'm recommending we leave it there.

Fixed object-type detection of the `CMB2::current_object_type()` method

---

example-functions.php

Some PHPCS fixes for example-functions file

Example functions clean up

---

.travis.yml

WordPress' test suite fails on PHP7 in Travis currently because of the version of PHPUnit (6) Travis includes on their PHP7.x builds.
[Core ticket 40086](https://core.trac.wordpress.org/ticket/40086) fixes this until [WordPress' test suite is updated to support PHPUunit 6](https://core.trac.wordpress.org/ticket/39822).
This pull should pass on PHP7 instead of allowing it to fail.

Get PHP7 builds to pass on Travis again.

---

tests/test-cmb-types-base.php

Multiline array, trailing commas

Fix WP VIP PHPCS in tests/test-cmb-types-base

---

example-functions.php

Indentation, no actual code changes

Fix WP VIP PHPCS in example-functions

---

CHANGELOG.md
includes/CMB2.php

This is a backwards-compatibility break. If your theme or plugin is using some of next action hooks and your are connecting the output between them then take a look a this explanation
Hooks have been called in this order (until this PR):
`cmb2_before_form`
`cmb2_before_{$object_type}_form_{$cmb_id}`
`cmb2_after_form`
`cmb2_after_{$object_type}_form_{$cmb_id}`
And now they are called at this order:
`cmb2_before_form`
`cmb2_before_{$object_type}_form_{$cmb_id}`
`cmb2_after_{$object_type}_form_{$cmb_id}`
`cmb2_after_form`
Why? Because this means call this hooks is really dangerous because you could break your html if you expect a relative order, for example, if two plugins using this hooks to print something, the most common workflow is use same relative callbacks (`cmb2_before_form` and …

Before and after form hooks order

---

includes/CMB2_hookup.php

-  Adding the current CMB2 box object as a parameter to the 'cmb2_can_save' filter so we can identify which box is being saved.
-  It allows us to easily get and verify the box nonce into our custom filter for example.

Updates 'cmb2_can_save' filter

---

includes/CMB2_Options.php
tests/test-cmb-core.php

The method just return cast `$this->options` as array but actually `$this->options` assign before still a string in some case.
Bugs will be show when I try empty cmb setting in `wp_options` table.

Cast variable

---

includes/CMB2_Types.php

In v2.2.4, a bug was introduced where custom fields were not available as a repeatable field. This was only happening to fields that were added using the `cmb2_render_{$field_type}` action hook. Fields rendered by a class extending `CMB2_Type_Base` class were unaffected by this.
Currently, the `maybe_custom_field_object` always returns the $type property. This is causing the `__call()` function to never reach the `cmb2_render_{$field_type}` action hook.
This pull fixes #901, and improves the PHPDocblock for the function.

Custom fields not available as repeatable

---

includes/CMB2_Sanitize.php

Restore `wp_unslash()` for money values

---

js/cmb2.js

Fixes #1035 and #348. Possibly related to #712 and others.
-  Pass the `group` boolean into `cmb.elReplacements` so it can know which index to replace for new Name and new IDs.
-  If the new replacements are for a group, use a regex that won't match a field's attributes.
-  If the new replacements are not for a group, use a regex that finds matches at the end of the field attribute strings, avoiding the group-level values within those attributes.
- When a new group is added, fix the name and ID attributes on the hidden `.empty-row`s so that the next "Add Row" has the correct attributes.

Fix repeating fields within repeating groups by changing regex depending on context

---

CHANGELOG.md
example-functions.php
includes/CMB2.php
includes/CMB2_Options.php
includes/CMB2_Options_Hookup.php

Fixes #1093.
Ability to disable the options autoload parameter via filter (`"cmb2_should_autoload_{$options_key}"`) or via a box parameter for `'options-page'` box registrations (`'autoload' => false,`).

Ability to autoload=false for options. Closes #1093

---

CONTRIBUTING.md

Due to offline WP-Translations.
-  Fixes wrong translation URL

Updated translation section in CONTRIBUTING.md

---

includes/CMB2_Options_Hookup.php

Fixes #1095 and adds options page support for WP prior to 4.7, which otherwise crashed because of `register_setting` function been moved to `/wp-includes/option.php` in WP 4.7 because of [this](https://core.trac.wordpress.org/ticket/37885).

Fix the options page issue in WP prior to 4.7

---

includes/CMB2_Options_Hookup.php

Fixes the error caused when passing an object method to `display_cb`, therwise it results in **Fatal error**: **Function name must be a string in**

use "call_user_func()" instead of direct call.

---

includes/CMB2_hookup.php

**v2.3.0** as well as tested against trunk.
**Issue**
Taxonomy fields accept a 'remove_default' parameter which unregisters the default term meta box on the post edit screens. This parameter works fine if you are using a standard meta box context when registering the meta box. However if you use another context such as 'after_title' this 'remove_default' parameter does nothing.
**To Recreate:**
Use a context when registering a box such as 'after_title'
Add a field of a taxonomy type and pass 'remove_default' to the field
See the default taxonomy meta box still exists on post edit screens
**Solution**
This pull request decouples the remove_default_tax_metabox() method from the add_metaboxes() method and calls it on it's own independent 'add_meta_boxes' action which allows the …

Call remove_default_tax_metaboxes from any type of post_hooks

---

includes/CMB2_Types.php

This change removes unneeded method definitions from the class DocBlock. These methods are defined within the class, and so the `@method` tags aren't necessary (and in fact result in inspection errors in IDEs; in PhpStorm they trigger a "Method with same name already defined in this class" error).
Reference: http://docs.phpdoc.org/references/phpdoc/tags/method.html

Remove superfluous method definitions

---

.gitignore
composer.json
composer.lock

Fixes #1203.
- add `composer.lock` into the repo
- up the `phpunit` version to `6.5.*` so tests will start working when running a locally project-level installed phpunit

Update PHPUnit version in composer.json

---

package-lock.json
package.json

Fixes #1205.
- included package-lock.json file as per [npm docs](https://docs.npmjs.com/files/package-lock.json).
- updated `grunt` to 0.4.5
- added local project-level `grunt-cli` dependency
- added an ability to run a local project-level version of grunt via `npm run grunt`

Package.json: fix the need of global (old) grunt

---

includes/CMB2_Field.php

The CMB2_Field has support for a (currently undocumented) property named `rest_value_cb` within the `get_rest_value` method. 
Currently, there is a `apply_filters` call which does nothing because it does have set a value when invoked. The second argument passed to `apply_filters` is 99 which suggests this is actually a priority vs a magic number. 
Changing `apply_filters` to `add_filter` allows this property to work while leaving the arguments intact. 
Change `apply_filters` to `add_filter`.

Fix `rest_value_cb` registering of filter

---

includes/CMB2_Field.php
includes/CMB2_Types.php
tests/test-cmb-types.php

Fixes #1214.
- When there is a repeatable field - register a `jquery-ui-sortable` lib as a dependency for default `cmb2.js`.

Making a field repeatable generates JS error because of missing sortable lib

---

.gitattributes

When installing CMB2 via Composer, the composer.json file gets excluded from the package. While this file isn't strictly needed, it helps if this file is in place when you're checking dependencies in your project.
In addition, the composer.lock file _doesn't_ get excluded, which is weird.
After installing CMB2 via Composer, I wanted to quickly check its dependencies but was unable to do so.
Low
1. Run `mkdir composer-export && git archive HEAD | tar -xC composer-export`
2. Verify that composer.json is present in the `composer-export` directory

Don't exclude composer.json from the distribution

---

README.md

The facetwp-cmb2 plugin was linked to facetwp/facetwp-cmb2. 
I changed the hyper reference to WebDevStudios/facetwp-cmb2.
Users can find the WebDevStudios/facetwp-cmb2 via the README.md more easily.
low
manual tested the new link

Corrected link to facetwp-cmb2 in README.md

---

includes/CMB2.php

Removing `strip_tags()` since it is already run within `sanitize_text_field()` per WP VIP Feedback.
Removes unnecessary call to `strip_tags`.
Minimal risk

Removing strip_tags() since it is already run in sanitize_text_field().

---

includes/CMB2.php

Wrapping the return of `CMB2->box_classes()` in `sanitize_html_class()` per WP VIP Feedback.
Sanitizes the class of the CMB2 box.
Minimal risk
1. Add filter to `cmb2_wrap_classes` to add some class names with quotes or special characters.
2. Create CMB2 metabox.
3. Check CMB2 metabox classes.

Wrap the return of CMB2->box_classes() in sanitize_html_class() per VIP Feedback

---

includes/CMB2.php

Sanitizing data from $_REQUEST input within CMB2.php per VIP feedback.
Sanitizing data from $_REQUEST input within CMB2.php to pass WordPress-VIP-Go coding standards.
Minimal risk

Sanitizing data from $_REQUEST input within CMB2.php

---

includes/CMB2_Field_Display.php

Picking off some escaping/sanitizing from #1260. This PR late-escapes output from the `file_output` method of the `CMB2_Display_File` class. I realize that we're already escaping the URL in https://github.com/CMB2/CMB2/blob/develop/includes/CMB2_Field_Display.php#L397, but late-escaping is preferred and we could possibly get rid of the early-escaping from the link above.
Hardening escaping and sanitizing throughout the plugin.
Minimal risk

Add late escaping to CMB2_Display_File

---

includes/CMB2_Field_Display.php
includes/CMB2_Options_Hookup.php
includes/CMB2_Types.php

Picking off some escaping/sanitizing from https://github.com/CMB2/CMB2/issues/1260. Ensures that classes with dynamically-inserted classes are properly escaped and (in this case) sanitized.
Hardening escaping and sanitizing throughout the plugin.
Minimal risk

Ensure HTML classes are escaped

---

init.php

Add function_exists('add_action') check to initialization file. When
loading CMB2 via Composer (and autoloading init.php), the init.php will
be loaded every time. Usually this is not a problem, however if we are
also using Composer to load a PHP development tool (e.g. PHP Codesniffer
(phpcs)), when the development tool runs it is NOT in the context of
WordPress.
Running CMB2's init.php outside of the context of WordPress
results in a fatal error because the function add_action() does not
exist. By adding this function_exists() check, we can avoid this fatal
error when autoloading init.php outside of the context of WordPress.
See #1270
Check that the `add_action()` function exists before calling it in `init.php`.
Fixes #1270.
This seems to be a relatively low risk change. Since we're …

Add function_exists('add_action') check

---

includes/CMB2_hookup.php

Added support to sort columns automatically by the type of field text, number, date or time.
Added support to sort columns automatically in admin tables list when the "column" attribute is true.
This will sort by field type (text, number, date or time) using (query "orderby" -> meta_value, meta_value_num, meta_value_time or meta_value_date accordingly).
There was a need to sort columns generated by CMB2 automatically without custom code. 
Fixes #831.
minimal risk
Using the example-functions.php you can verify that the field with column attribute defined will automatically be able to sort. 
**New feature (non-breaking change which adds functionality)**

Added support for sortable columns

---

includes/types/CMB2_Type_File.php

Adds some attribute escaping that was missed
This PR adds additional escaping to the file field
This improves the security of the file field type
admin-only, minimal risk
I ran the code and confirmed no changes in WP Admin

Escaping improvements to File Fields

---

js/cmb2.js

Fixes #1299.
See #1299 for more details.
Low.
1. Clear browser cache if necessary
1. Follow the steps outlined in #1299 to create a repeatable `textarea_code` field
1. Click and drag to try to select text in the CodeMirror area. The whole block should **not** drag

Include .CodeMirror class in sortable exclusions

---

includes/CMB2_Sanitize.php

The new field type "taxonomy_select_hierarchical" did not save the data to the right table.
I have added a line of code into CMB2_Sanitize->default_sanitization() in order to save the taxonomy_* in to right table.
When I tried to work on this new field type, it did not save the data into the right table, it suppose to update  the table _term_relationships instead it save the data into _postmeta
I have tested this code directly in my project. I have a list of custom_type taxonomies for a custom post_type. and with this modification it works as expected in my local, and prod environments.
NOTE: I have dowloaded the project from CMB2:develop branch.

Add "taxonomy_select_hierarchical" in CMB2_Sanitize->default_sanitization()

---

.travis.yml

As cmb2 is [published on packagist](https://packagist.org/packages/cmb2/cmb2) we must have a valid composer.json file.

Validate composer.json

---

bootstrap.php
includes/CMB2.php
includes/CMB2_Hookup.php
includes/CMB2_Options_Hookup.php
includes/helper-functions.php

Rename CMB2_hookup to CMB2_Hookup

---

includes/CMB2_JS.php

For some reason, WordPress stops to enqueue wp-color-picker by default on post edit screens
This PR adds an extra check to enqueue wp-color-picker if hasn't enqueued yet
Fixes #1338

Ensure to enqueue wp-color-picker

---

includes/types/CMB2_Type_Wysiwyg.php

This PR fixes an issue where the WYSIWYG field isn't working in a group.
When refactoring the WYSIWYG field in https://github.com/CMB2/CMB2/commit/7bb887c8fc89cb76570433b436e3d6ca914ebcf9#diff-73510adb75ef05f23da2023345b5cf0dR49 the issue was introduced. `'wp-util', 'cmb2-wysiwyg'` should be `array( 'wp-util', 'cmb2-wysiwyg' )`.
I use the wysiwyg field in a group and just noticed it stopped working, while it was working before.
I think the risk level should be low.
Add a wysiwyg field to a group, it'll be displayed as a textarea, tinyMCE isn't initiated on it.

Fix WYSIWYG filed not working in a group

---

includes/CMB2_Base.php

In `/includes/CMB2_Base.php`, in the `deprecated_param` method, `$args = func_get_args();` is currently inside the `is_numeric` if statement. This change moves it to the beginning of `deprecated_param` instead.
Fixes #1389. PHP 7.4 raises a warning without this change.
I've tested this on the `develop` branch of CMB2. I added a new field, using the `default` param instead of `default_cb` to raise the deprecated warning. It raises this log message:
```php
[05-Jan-2021 18:52:51 UTC] PHP Notice:  CMB2_Field::__construct() was called with a parameter that is <strong>deprecated</strong> since version 2.2.3! Using the "default" field parameter as a callback has been deprecated in favor of the "default_cb" parameter. in /vanilla-wordpress/wp-content/plugins/cmb2/includes/CMB2_Base.php on line …
```

move $args in deprecated_param method for PHP 7.4

---

includes/CMB2_Sanitize.php

URLs without a scheme now get HTTPS as the default, not HTTP.
Avoids information disclosure / malicious redirection.
Fixes #1412.
minimal risk
Tested by passing in URLs with no scheme, http: and https:

Sanitize URLs with HTTPS

---

includes/types/CMB2_Type_Multi_Base.php

Prevents deprecation notice: 
Deprecated: Required parameter $i follows optional parameter $args in /../vendor/cmb2/cmb2/includes/types/CMB2_Type_Multi_Base.php on line 34
Fixes #{issue-number}.
- **New feature (non-breaking change which adds functionality)**
- **Breaking change (fix or feature that would cause existing functionality to change)**

Bug Fix - CMB2_Type_Multi_Base.php

---

.github/workflows/test.yml
.gitignore
.wp-env.json
cypress.env.json.EXAMPLE
cypress.json
package-lock.json
package.json
tests/cypress/fixtures/example.json
tests/cypress/integration/activatePlugin.spec.js
tests/cypress/integration/login.spec.js
tests/cypress/integration/metaBoxes.spec.js
tests/cypress/plugins/index.js
tests/cypress/support/commands.js
tests/cypress/support/index.js
tests/cypress/support/test-fields.php

Establishes a Cypress end-to-end testing framework, some tests, and GitHub Actions Setup.
Installs Cypress, sets up the ability to spin up a @wordpress/env environment in Docker on the fly, and adds some tests for it.
Additionally, it automatically runs the end-to-end tests in GitHub.
I intend to add a lot more tests, but even this base is useful in that it'll flag issues with logging in to WordPress, activating the plugin, or basic config/saving of CMB2 metaboxes.
More confidence in the codebase, and making it easier to trust PRs that touch hairy JavaScript code paths, like repeating groups.
Low. It doesn't change any core code.
CLI:
```bash
npm i
npm run cypress
npm run env stop
```
With Cypress GUI:
```bash
npm i
npm run env start
npx cypress open
npm run env stop
```

Establish Cypress E2E Testing

---

includes/CMB2_JS.php

we can not use rgba color picker in wordpress 5.5, because of console error.
Uncaught ReferenceError: wpColorPickerL10n is not defined
in wordpress 5.5 we can not use rgba color picker because js variable is not defined :
Uncaught ReferenceError: wpColorPickerL10n is not defined
this variable is deleted is wordpress 5.5 and we added it in cmb2
because we can not use rgba colorpicker in wordpress 5.5
Fixes #{issue-number}.
https://github.com/CMB2/CMB2/issues/1373
https://github.com/CMB2/CMB2/issues/1368
admin-only = minimal risk
test it in wordpress 5.5

FIX(colorpicker rgba) :: using rgba color picker for wordpress 5.5

---

includes/CMB2_Hookup.php

Add 'woocommerce_page_wc-orders' to $hooks array in do_scripts() so that CMB2 styles are loaded on WooCommerce Edit Order page when HPOS enabled.
CMB2 styles are loaded on a number of admin pages but not the WooCommerce Edit Order page when HPOS is enabled. This page uses admin.php but adding that did not work so I added 'woocommerce_page_wc-orders' to the array.
Related to adding a metabox on a WooCommerce Edit Order page when HPOS enabled.
https://wordpress.org/support/topic/how-do-i-show-metabox-on-woocommerce-order-page-for-hpos-setup/
and my code to add tracking info to a WooCommerce order email
https://www.damiencarbery.com/2020/01/add-tracking-info-to-woocommerce-order/
admin-only, probably minimal risk.
I tested the code by loading the WooCommerce Edit Order page without and with …

Load styles on WooCommerce HPOS order page

---

.github/workflows/phpcompat.yml

Adds a PHP Compatibility action to that validates against [PHPCompatibility](https://github.com/PHPCompatibility/PHPCompatibility)
Should alert in the future if any change is not compatible with the latest PHP version. Will need to be updated for PHP 8.3, 8.4, 9.0, etc.
minimal risk -- this only runs in the repository. The potential gain is big, though, because it should, in theory, catch any PHP compatibility issues.
I'm somewhat suspicious of the passing tests now, however, because it seems like they may be false positives, but with the action in place and set, issues can be reported to https://github.com/pantheon-systems/phpcompatibility-action/issues if it seems like we're not getting appropriate flagging.
Self-testing. This PR is, itself, a test. 😀 
**New feature (GH action)**

add a phpcompatibility action

---

.github/workflows/phpcompat.yml

Uses the `dev` branch of the `phpcompatibility-action` rather than the `v1`
`v1` uses the stable, 9.3 version of the PHPCompatibility sniffs, however that version does not include any 8.x checks, so running `8.x-` doesn't check anything valuable.
The `dev` branch of the action pulls the `develop` branch of PHPCompatibility, which _does_ include 8.x sniffs.
minimal (although we should get errors for PHP 8.x compatibility)
Should be evident in the tests...
- **New feature (non-breaking change which adds functionality)**

use `dev` instead of `v1` for `phpcompatibility-action`
