includes/CMB2_hookup.php
@jtsternberg requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/WebDevStudios/CMB2/
=> Scrutinizer Auto-Fixes

js/cmb2.js
=> Fix delete row from repeatable group. Fixes #281

includes/CMB2_Utils.php
returning `string` type `$string` when condition enters `else` during the creation of valid timestamp to save in the database.
=> Returning String type

init.php
=> load_theme_textdomain expects an absolute path

js/cmb2.js
Really trying to get these fixes into the live deployed plugin. Please review the fix to #152. Thanks!
=> fix issue #152

readme.md
Just a small README capitalization fix.
=> Fix WordPress capitalization

js/cmb2.js
Can't wait for these changes in the Wordpress.org version!
=> fixes #187 where sorting filelists don't save in repeatable groups

.gitattributes
=> Export the same files as the wordpress.org plugin repository

includes/CMB2_Field.php, includes/CMB2_Sanitize.php
* Fix typo.
* Fix turned around documentation.
=> Minor documentation fixes.

tests/test-cmb-field.php
=> Add unit tests for save_field

tests/README.md, tests/bootstrap.php
Fixes #714.
-  Update docblock for tests\bootstrap.php
-  Fix a typo in the tests\README.md
-
=> Fixes #714 - docblock in tests\bootstrap.php out of date

README.md
Added [CMB Field Type: Order](https://github.com/rubengc/cmb2-field-order) and [CMB Field Type: Animation](https://github.com/rubengc/cmb2-field-animation)
=> More 3rd party resources

includes/CMB2_Ajax.php
Multiline array, mark end of long if
=> Phpcs wp vip fixes/includes/cmb2 ajax

tests/test-cmb-utils.php
=> Fix WP VIP PHPCS in tests/test-cmb-utils

tests/test-cmb-types.php
=> Fix WP VIP PHPCS in tests/test-cmb-types

tests/test-cmb-types-display.php
=> Fix WP VIP PHPCS in tests/test-cmb-types-display

tests/test-cmb-rest.php
=> Fix WP VIP PHPCS in tests/test-cmb-rest

tests/test-cmb-rest-controllers.php
=> Fix WP VIP PHPCS in tests/test-cmb-rest-controllers

tests/test-cmb-field.php
=> Fix WP VIP PHPCS in tests/test-cmb-field

tests/test-cmb-rest-registered-fields.php
=> Phpcs wp vip fixes/tests/test cmb rest registered fields

includes/CMB2_Field.php
Multiline array, mark long ifs
=> Phpcs wp vip fixes/includes/cmb2 field

tests/test-cmb-core.php
=> Fix WP VIP PHPCS in tests/test-cmb-core

tests/test-cmb-ajax.php
Multiline array, trailing comma, spacing
=> Fix WP VIP PHPCS in tests/test-cmb-ajax

tests/cmb-tests-base.php
=> Fix WP VIP PHPCS in tests/cmb-tests-base

tests/cmb-rest-tests-base.php
=> Fix WP VIP PHPCS in tests/cmb-rest-tests-base

init.php
=> Fix WP VIP PHPCS in init

includes/types/CMB2_Type_Wysiwyg.php
=> Fix WP VIP PHPCS in includes/types/CMB2_Type_Wysiwyg

includes/types/CMB2_Type_Taxonomy_Select.php
=> Fix WP VIP PHPCS in includes/types/CMB2_Type_Taxonomy_Select

includes/types/CMB2_Type_Taxonomy_Radio.php
=> Fix WP VIP PHPCS in includes/types/CMB2_Type_Taxonomy_Radio

includes/CMB2.php
=> Fix WP VIP PHPCS in includes/CMB2

includes/CMB2_Field_Display.php
Make arrays multiple lines, mark long loop
=> Fix WP VIP PHPCS in includes/CMB2_Field_Display

includes/CMB2_JS.php
=> Fix WP VIP PHPCS in includes/CMB2_JS

includes/CMB2_Utils.php
Mark long loop, fixing empty new line
=> Fix WP VIP PHPCS in includes/CMB2_Utils

includes/helper-functions.php
=> Fix WP VIP PHPCS in includes/helper-functions

includes/rest-api/CMB2_REST_Controller.php
=> Fix WP VIP PHPCS in includes/rest-api/CMB2_REST_Controller

includes/rest-api/CMB2_REST_Controller_Boxes.php
=> Fix WP VIP PHPCS in includes/rest-api/CMB2_REST_Controller_Boxes

includes/rest-api/CMB2_REST_Controller_Fields.php
=> Fix WP VIP PHPCS in includes/rest-api/CMB2_REST_Controller_Fields

includes/types/CMB2_Type_Taxonomy_Multicheck.php
=> Fix WP VIP PHPCS in includes/types/CMB2_Type_Taxonomy_Multicheck

includes/types/CMB2_Type_Taxonomy_Base.php
=> Fix WP VIP PHPCS in includes/types/CMB2_Type_Taxonomy_Base

includes/types/CMB2_Type_Oembed.php
=> Fix WP VIP PHPCS in includes/types/CMB2_Type_Oembed

includes/shim/WP_REST_Controller.php
=> Fix WP VIP PHPCS in includes/shim/WP_REST_Controller

includes/types/CMB2_Type_File.php
=> Fix WP VIP PHPCS in includes/types/CMB2_Type_File

.github/ISSUE_TEMPLATE.md
- Adds note about using wordpress.org for initial support and questions.
=> Issue template support touchup

README.md
=> Added Skeleton in helpful resources!

css/sass/cmb2.scss, css/sass/partials/_collapsible_ui.scss, css/sass/partials/_main_wrap.scss, css/sass/partials/_misc.scss, css/sass/partials/_mixins.scss, css/sass/partials/_options-page.scss
=> Improve options page style

includes/shim/WP_REST_Controller.php, readme.txt
Minor spelling corrections found while translating for en_CA
=> Spelling Corrections

README.md
Maybe this helpful for someone looking for.
=> Add icon-picker field type

includes/types/CMB2_Type_Associated_Objects.php
First pass at making field flexible for many different types of objects.
See: #1055
=> Query work on new associated-objects field type

js/cmb2.js
=> Fixed #1058

includes/CMB2.php
=> ensure the cmb2 ajax object loads

README.md
Just created a new 3rd party fieldtype for selecting Font Awesome Icons.
[CMB2 Field Type: Font Awesome Icon Selector](https://github.com/serkanalgur/cmb2-field-faiconselect)
=> Added 3rd Party Fieldtype

readme.txt
Adding a new typography field :)
Fixes #{issue-number}.
-  
-  
-
=> Adding a new typography field :)

README.md, readme.txt
Fixes #{issue-number}.
-  
-  
-
=>  Include CMB2 Admin Extension in the list of resources

README.md
Smart Select field for CMB2 with "optgroup" and "multiple" attribute support
=> Added new custom field type

.gitattributes
Related: #1225 and d77e89f.
This changes removes some more unnecessary directories from the package distribution.
=> Ignore some more directories in the distribution package

README.md, readme.txt
Update WordPress tested tag
Reflect that the plugin works with the latest version of WordPress
No Risk
=> Update WordPress tested tag

includes/types/CMB2_Type_File_Base.php
Improves the escaping of some output in the File Base field type
admin-only
=> Escaping Improvements to File Base

LICENSE
Meet Community standards as in https://github.com/CMB2/CMB2/community
no risk
**License**
=> Add license file to meet Community standards

CODE_OF_CONDUCT.md
=> Proposal of CODE OF CONDUCT File

README.md
ref https://github.com/CMB2/CMB2/issues/1457
=> Remove field from readme

README.md
Update WordPress Tested up to tag 6.1
minimal risk
- **New feature (non-breaking change which adds functionality)**
=> Update WordPress Tested up to tag 6.1
